### ISSUE TITLE
[REQUEST] Allow for changing your username in the config file

### ISSUE THREAD

**Issue by CenTdemeern1** [MBU-Team/OpenMBU#119] opened 2022-01-06 12:10 UTC
Currently the game takes the username directly from the system, which can be kind of annoying if it has your real name in it.
Can this maybe be changed to work like this:
- If the username field isn't present in the config file:
-> Add it and set it to the system name by default
- Else:
-> Read username from the config file

**Comment by CenTdemeern1** [comment] 2022-01-06 12:17
I just disconnected from my Microsoft account just so I can use something that's not my real name

**Comment by thearst3rd** [comment] 2022-01-06 16:48
Duplicate of #96. Also, I made a pull request that does exactly this (#102) but @HumanGamer didn't want to merge it because of the upcoming online system. Maybe this will convince him? ;)

**Comment by RandomityGuy** [comment] 2024-03-17 09:17
Implemented in https://github.com/MBU-Team/OpenMBU/commit/065dfdc8f6a714ae8547ca10f2252700d2e21c48

**Closed by RandomityGuy** 2024-03-17 09:17 UTC
Labels: enhancement
