### ISSUE TITLE
[BUG] Uncollectable Gem Glitch

### ISSUE THREAD

**Issue by neolightning** [MBU-Team/OpenMBU#90] opened 2021-05-30 19:19 UTC
Sometimes a gem spawn will not be collectable

All gems should be collectable and de spawn until the next gem group is ready.

**Comment by thearst3rd** [comment] 2021-12-26 16:29
Closing since nobody has reproduced this since the hifi fixes were merged. If it happens again, we'll reopen.

**Closed by thearst3rd** 2021-12-26 16:29 UTC
Labels: bug
