### ISSUE TITLE
[BUG] Glass cannot been seen through other glass

### ISSUE THREAD

**Issue by MrTwatWaffle** [MBU-Team/OpenMBU#89] opened 2021-05-29 21:23 UTC
![image](https://user-images.githubusercontent.com/50997466/120084964-57249580-c089-11eb-840e-38766c341a40.png)

**Comment by neolightning** [comment] 2021-05-29 21:35
We know about this, the render system has to be redone most likely to fix it

**Comment by HumanGamer** [comment] 2021-05-29 22:08
Duplicate of #35

**Closed by HumanGamer** 2021-05-29 22:08 UTC
Labels: bug, duplicate
