### ISSUE TITLE
[BUG] Gem pickup text is missing.

### ISSUE THREAD

**Issue by BlastedMarble** [MBU-Team/OpenMBU#208] opened 2024-03-13 18:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Beta 1.16

### OS

Windows 10

### Steps to reproduce

Collect a gem in a level that has gems.

### Expected Behavior

A text at the bottom should say "You picked up a gem, X gems to go".

### Actual Behavior

No such text shows up.

### Reproduction frequency

It's been happening in the latest beta.

**Comment by thearst3rd** [comment] 2024-03-13 19:49
Pretty sure this is a duplicate of #172, resolved in #178

**Closed** 2024-03-29 13:36 UTC
Labels: bug
