### ISSUE TITLE
[BUG] Ghost Beam On Multiplayer Gems

### ISSUE THREAD

**Issue by neolightning** [MBU-Team/OpenMBU#71] opened 2021-05-18 02:56 UTC
Ghost Beam On Multiplayer Gems

Beam should be removed when gem is collected

**Comment by HumanGamer** [comment] 2021-05-19 18:18
If anybody is able to reproduce this, please share what you did, and provide console.log

**Comment by thearst3rd** [comment] 2021-12-26 16:29
Closing since nobody has reproduced this since the hifi fixes were merged. If it happens again, we'll reopen.

**Closed by thearst3rd** 2021-12-26 16:29 UTC
Labels: bug
