### ISSUE TITLE
[BUG] Collecting a TT and then restarting the level will cause the TT sound to continue playing until you restart the level again

### ISSUE THREAD

**Issue by MrTwatWaffle** [MBU-Team/OpenMBU#88] opened 2021-05-29 21:19 UTC
Collecting a TT and then restarting the level will cause the TT sound to continue playing intel you restart the level again

**Comment by HumanGamer** [comment] 2021-06-23 17:11
@MrTwatWaffle I can't reproduce this on Beta 1.6. Does this still happen?

**Comment by HumanGamer** [comment] 2021-06-23 17:22
This seems to have been fixed at some point, and I have no idea why. Closing.

**Closed by HumanGamer** 2021-06-23 17:22 UTC
Labels: bug
