### ISSUE TITLE
[BUG] Game crashes if exited from full-screen

### ISSUE THREAD

**Issue by CDAGaming** [MBU-Team/OpenMBU#73] opened 2021-05-18 17:42 UTC

**Comment by HumanGamer** [comment] 2021-05-18 18:06
When you say fullscreen, did you use the console and activate Exclusive Fullscreen? or do you just mean Borderless Fullscreen from the video options. If so, does it happen every time?

**Comment by CDAGaming** [comment] 2021-05-18 20:03
It was borderless fullscreen (no console) and Ive only tried it once while testing this morning. Ill try to get another case of it the next time I test this.

**Comment by MrTwatWaffle** [comment] 2021-05-19 01:04
I have tested this now multiple times with no crash it must of just been a one time instance!

**Comment by HumanGamer** [comment] 2021-05-19 18:14
I will leave this open for now. If it happens again, can you let me know? And provide the console.log next time if possible. Also using the debug version should spew more output but may not perform as well if you'd be willing to use that one.

**Comment by HumanGamer** [comment] 2021-05-21 19:07
It's possible this is caused by an issue with saving fonts.

When it crashed, did it pop up a dialog of some kind? If so, what did it say? If not, how do you know it crashed?

**Comment by CDAGaming** [comment] 2021-05-21 21:08
It just had the normal not responding popup, though it only happened once, so possible edge case

**Comment by HumanGamer** [comment] 2021-05-22 22:53
Alright, I'm going to close this for now. We can re-open it if it keeps happening.

**Closed by HumanGamer** 2021-05-22 22:53 UTC
Labels: bug
